#!/usr/bin/env bash
source common

if [[ ! -e Makefile ]]; then { error "Not in a kernel directory! Exiting..."; exit 1; }; fi

GCC_DIR="/media/shagbag913/Roms/kernel/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-"

make mrproper
make clean

export ARCH=arm64
make shag_defconfig

if [[ ${1} = "-c" ]]; then
    info "Building with Clang"
    make "${PAR_THREAD}" \
        CC="ccache /media/shagbag913/Roms/kernel/toolchains/linux-x86/clang-r328903/bin/clang" \
        CLANG_TRIPLE=aarch64-linux-gnu- \
        CROSS_COMPILE="${GCC_DIR}" && SUCCESS=true
fi

if [[ ${1} = "-g" ]]; then
    info "Building with GCC"
    make "${PAR_THREAD}" \
        CROSS_COMPILE="ccache ${GCC_DIR}" && SUCCESS=true
fi

if [[ ${SUCCESS} = true ]]; then
    info "Kernel build successful!"
    cd /media/shagbag913/Roms/kernel/shagkernel/ak2 || { error "Couldn't find AnyKernel2 folder!"; exit 1; }
    cp /media/shagbag913/Roms/kernel/shagkernel/arch/arm64/boot/Image.lz4-dtb .
    ./zip.sh
    cd /media/shagbag913/Roms/gdrive || { warn "Couldn't find GDrive folder! Not uploading to gdrive.."; exit 1; }
    rm -rf Kernel/*
    cp /media/shagbag913/Roms/kernel/shagkernel/ak2/ShagKernel*.zip ./Kernel
    grive
    info "Kernel uploaded to GDrive"
fi
