#!/usr/bin/env bash
# FETCH AFH PASSWORD #
pas=$(cat /media/shagbag913/Roms/.pas)

out=out/target/product/sailfish

# BUILD DIRECTORIES
bdir1=/media/shagbag913/Roms/roms/aex
bdir2=/media/shagbag913/Roms/roms/du
bdir3=/media/shagbag913/Roms/roms/dot
bdir4=/media/shagbag913/Roms/roms/aicp

### FUNCTIONS ###
autopilot() {
## AEX ##
   cd $bdir1
   sync
   lunchh
   lunch aosp_sailfish-userdebug
   echo "**Building AospExtended**" | python3 ~/localscripts/dis.py
   make aex -j6
      if [ "$?" = "0" ]; then
         echo "*AospExtended Built Successfully!*" | python3 ~/localscripts/dis.py
      else
         echo "*AospExtended Failed...*" | python3 ~/localscripts/dis.py
      fi
   curl -T `ls -rt ${out}/AospExtended-v5*.zip | tail -1` ftp://shagbag913:$pas@uploads.androidfilehost.com
## DU ##
   cd $bdir2
   sync
   echo "**Building Dirty Unicorns**" | python3 ~/localscripts/dis.py
   brunchh
      if [ "$?" = "0" ]; then
         echo "*Dirty Unicorns Built Successfully!*" | python3 ~/localscripts/dis.py
      else
         echo "*Dirty Unicorns Build Failed...*" | python3 ~/localscripts/dis.py
      fi
   curl -T `ls -rt ${out}/du_sailfish-v*.zip | tail -1` ftp://shagbag913:$pas@uploads.androidfilehost.com
## DOT ##
   cd $bdir3
   sync
   echo Copying theming patch
   rm -rf /media/shagbag913/Roms/roms/dot/build/core/build_rro_package.mk
   cp /media/shagbag913/Roms/patches/build_rro_package.mk /media/shagbag913/Roms/roms/dot/build/core/build_rro_package.mk
   echo "**Building dotOS**" | python3 ~/localscripts/dis.py
   brunchh
      if [ "$?" = "0" ]; then
         echo "*dotOS Built Successfully!*" | python3 ~/localscripts/dis.py
      else
         echo "*dotOS Build Failed...*" | python3 ~/localscripts/dis.py
      fi
   curl -T `ls -rt ${out}/dotOS-O-*.zip | tail -1` ftp://shagbag913:$pas@uploads.androidfilehost.com
## AICP ##
   cd $bdir4
   sync
   echo "**Building AICP**" | python3 ~/localscripts/dis.py
   brunchh
      if [ "$?" = "0" ]; then
         echo "*AICP Built Successfully!*" | python3 ~/localscripts/dis.py
      else
         echo "*AICP Build Failed...*" | python3 ~/localscripts/dis.py
      fi
   curl -T `ls -rt ${out}/aicp_sailfish_o-13.1*.zip | tail -1` ftp://shagbag913:$pas@uploads.androidfilehost.com
}
sync() {
   echo Syncing up $1...
   time (repo sync -j6 --no-tags --no-clone-bundle --force-sync -f -q)
   if [ "$?" = "0" ]; then
      echo Successfully synced!
   else
      echo Sync failed.
   fi
}
clean() {
   echo Cleaning outputs...
   cd $bdir1
   make clobber
   cd $bdir2
   make clobber
   cd $bdir3
   make clobber
   cd $bdir4
   make clobber
   echo Outputs cleaned.
   echo "**Outputs cleaned**" | python3 ~/localscripts/dis.py

}
brunchh() {
   time (echo Setting up build enviroment...
   . build/envsetup.sh
   echo Building...
   brunch sailfish)
   if [ "$?" = "0" ]; then
     echo Build Successful!
   else
      echo Error: build not successful.
   fi
}
lunchh() {
   echo Setting up build enviroment...
   . build/envsetup.sh
   echo Building...
}
while [ "$1" != "" ]; do
   case $1 in
      --brunch ) brunchh;;
      -s | --sync ) sync;;
      -c | --clean ) clean;;
      -a | --autopilot ) autopilot;;
      -u | --upload ) curl -T $2 ftp://shagbag913:$pas@uploads.androidfilehost.com;;
   esac
shift
done
