#!/bin/bash

# Source common stuff
source common

### Really ugly Kernel Build Script 
make mrproper
make clean
make shag_defconfig
make ${PAR_THREAD} && success=yes
if [[ ${success} = yes ]]; then
    cd /media/shagbag913/Roms/kernel/ak2
    rm -rf Image.lz4-dtb
    cp /media/shagbag913/Roms/kernel/shagkernel/arch/arm64/boot/Image.lz4-dtb .
    ./zip.sh
    cd /media/shagbag913/Roms/gdrive
    rm -rf Kernel/*
    cp /media/shagbag913/Roms/kernel/ak2/ShagKernel*.zip ./Kernel
    grive
fi
