#!/usr/bin/env bash

simg2img system.img system.raw
mkdir systemraw
sudo mount system.raw systemraw
sudo grep -r ro.bootimage.build.fingerprint systemraw/default.prop
sudo umount systemraw
rm -r systemraw
rm system.raw
