#!/usr/bin/env bash

: '
 This script contains common variables/functions
 that are used across the scripts in this directory.
'

BLUE='\e[0;34m'
GREEN='\e[0;32m'
RED='\e[0;31m'
YELLOW='\e[0;33m'
RESTORE='\e[0m'

DEVICE="sailfish"

# Number of parallel threads to use when compiling 
PAR_THREAD="-j$(($(nproc --all) * 2 - 2))"

# DISCORD CONFIG
# Discord script location
DC_SCRIPT="${HOME}/shagbot/dis.py"

# Check if discord script exists
dc_chk() {
if [[ ! -e ${DC_SCRIPT} ]]; then
    warn "Discord bot not found at ${DC_SCRIPT}!"
else
    DC=true
fi
}

# Message discord function
dc_msg() {
    echo "$1" | python3 "${DC_SCRIPT}"
}

# GOOGLE DRIVE CONFIG
# Check if "grive" is installed
grive_chk() {
if ! command -v grive > /dev/null; then
    warn "grive not installed! Not syncing to GDrive..."
else
    GDRIVE=true
fi
}

GD_FOLDER="/media/shagbag913/Roms/gdrive"

# BANNERS
error() {
    printf "${RED}"'%0.s-' $(seq 1 $((${#1}+7)))
    printf '\n%s\n' "ERROR: ${1}"
    printf '%0.s-' $(seq 1 $((${#1}+7)))
    printf '\n'
    printf "${RESTORE}"
}

warn() {
    printf "${YELLOW}"'%0.s-'  $(seq 1 $((${#1}+6)))
    printf '\n%s\n' "WARN: ${1}"
    printf '%0.s-' $(seq 1 $((${#1}+6)))
    printf '\n'
    printf "${RESTORE}"
}

info() {
    printf "${BLUE}"'%0.s-'  $(seq 1 $((${#1}+6)))
    printf '\n%s\n' "INFO: ${1}"
    printf '%0.s-' $(seq 1 $((${#1}+6)))
    printf '\n'
    printf "${RESTORE}"
}
