#!/usr/bin/env bash

set -e

URL=$1
DIR=$(pwd)
ZIP=$(basename ${URL})
IMAGE=$(echo ${ZIP} | awk -F-factory '{print $1}')
FOLDER=${DIR}/${IMAGE}
FOLDER_EXTRACTED=${FOLDER}/${IMAGE}_extracted
export FOLDER_BLOBS=${FOLDER}_blobs
mkdir -p ${FOLDER_BLOBS}
wget ${URL}
unzip ${ZIP}
cd ${FOLDER}
mkdir -p ${FOLDER_EXTRACTED}
unzip image-${IMAGE}.zip -d ${FOLDER_EXTRACTED}
cd ${FOLDER_EXTRACTED}
simg2img system.img system.raw
simg2img vendor.img vendor.raw
mkdir -p system_work
mkdir -p vendor_work
su -c 'mount -o loop system.raw system_work;
mount -o loop vendor.raw vendor_work;
cp -R system_work/* ${FOLDER_BLOBS};
cp --remove-destination -R vendor_work/* ${FOLDER_BLOBS}/vendor;
umount system_work;
umount vendor_work;
chown -R ${USER} ${FOLDER_BLOBS}'
rm -f ${ZIP}
rm -rf ${FOLDER}
cd ${DIR}
if [[ $2 = -r ]]; then 
    dev=${PWD}/device-proprietary-files.txt
    cp -r ${FOLDER_BLOBS}/vendor/app/* ${FOLDER_BLOBS}/system/priv-app/
    if ! grep -Fxq "# Vendor APKs" device-proprietary-files.txt; then
        echo "" >> ${dev}
        echo "# Vendor APKs" >> ${dev}
        echo "-priv-app/atfwd/atfwd.apk" >> ${dev}
        echo "-priv-app/colorservice/colorservice.apk" >> ${dev}
        echo "-priv-app/datastatusnotification/datastatusnotification.apk" >> ${dev}
        echo "-priv-app/embms/embms.apk" >> ${dev}
        echo "priv-app/embms/oem/config_params.xml" >> ${dev}
        echo "priv-app/embms/oem/provisioning_params.xml" >> ${dev}
        echo "priv-app/embms/oem/verizon_config_params.txt" >> ${dev}
        echo "-priv-app/fastdormancy/fastdormancy.apk" >> ${dev}
        echo "-priv-app/ims/ims.apk" >> ${dev}
        echo "-priv-app/imssettings/imssettings.apk" >> ${dev}
        echo "-priv-app/QAS_DVC_MSP/QAS_DVC_MSP.apk" >> ${dev}
        echo "-priv-app/QtiTelephonyService/QtiTelephonyService.apk" >> ${dev}
        echo "-priv-app/radioconfig/radioconfig.apk" >> ${dev}
        echo "-priv-app/RCSBootstraputil/RCSBootstraputil.apk" >> ${dev}
        echo "-priv-app/SecureExtAuthService/SecureExtAuthService.apk" >> ${dev}
        echo "-priv-app/shutdownlistener/shutdownlistener.apk" >> ${dev}
        echo "priv-app/SSRestartDetector/SSRestartDetector.apk" >> ${dev}
        echo "-priv-app/TimeService/TimeService.apk" >> ${dev}
        echo "-priv-app/vzw_msdc_api/vzw_msdc_api.apk" >> ${dev}
    fi
fi
