#!/usr/bin/env bash

FI_DOWNLOAD_DIR=/android/factimages
FI_ZIP=$(basename $1)
FI_FOLDER=$(echo $FI_ZIP | awk -F-factory '{print $1}')
DEVICE=$(echo $FI_ZIP | sed -n 's/-.*//p')
BUILD_NUM=$(echo $FI_ZIP | sed -n "s/-factory.*//; s/.*${DEVICE}-//p")
FI_SAVE_DIR=$FI_DOWNLOAD_DIR/$FI_FOLDER-images

cd $FI_DOWNLOAD_DIR
wget $1

unzip $FI_ZIP
cd $FI_FOLDER
unzip image-$FI_FOLDER.zip

mkdir $FI_SAVE_DIR
for i in vendor.img boot.img bootloader*.img radio*.img; do
    cp $i $FI_SAVE_DIR/
done

[[ -z $GD_DIR ]] && { echo "ERROR: GDrive folder not set! Aborting"; exit; }
mkdir $GD_DIR/Public/Images/$DEVICE/$BUILD_NUM
cp -r $FI_SAVE_DIR/* $GD_DIR/Public/Images/$DEVICE/$BUILD_NUM
grive -p $GD_DIR
