#!/usr/bin/env bash
source common

if [[ ! -e Makefile ]]; then error "Not in a kernel directory! Exiting..." && exit 1; fi

# Fetch/add stable remote if it does not exist
if git remote add linux-stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/ &>/dev/null; then
    info "Added remote 'linux-stable'"
fi

info "Fetching latest stable kernel tree"
git fetch linux-stable

# Current kernel version numbers
VER=$(make kernelversion)
MAJOR_VER=${VER%.*}

# Latest upstream version
LATEST_VER=$(git tag --sort=-taggerdate -l v"${MAJOR_VER}"* | head -n 1)

# Exit the script if the kernel version is already the latest
if [[ v${VER} = "${LATEST_VER}" ]]; then
    info "Kernel already up to date! :)" && exit 1
fi

# Merge!
if ! git merge "${LATEST_VER}"; then
    error "Merge failed! Fix the conflicts!"
fi
