#!/usr/bin/env bash
source common

if [[ ! -e Makefile ]]; then error "Not in a kernel directory! Exiting..." && exit 1; fi

# Fetch/add stable-rc remote if it does not exist
if git remote add linux-stable-rc https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/ &>/dev/null; then
    info "Added remote 'linux-stable-rc'"
fi

info "Fetching latest stable-rc kernel tree"
git fetch linux-stable-rc

# Current kernel version numbers
VER=$(make kernelversion)
MAJOR_VER=${VER%.*}

# Latest upstream version
LATEST_VER=$(git tag --sort=-taggerdate -l v"${MAJOR_VER}"* | head -n 1)

if [[ ${1} != "-rc" ]]; then
    if [[ v${VER} = "${LATEST_VER}" ]]; then
        info "Kernel already up to date! :)" && exit 1
    fi
    if ! git merge "${LATEST_VER}"; then
        error "Merge failed! Fix the conflicts!"
    fi
elif ! git merge linux-stable-rc/linux-${MAJOR_VER}.y; then
    error "Merge failed! Fix the conflicts!"
fi
